export const TEXT = {
    // GENERAL VARIABLES

    // Utils
    add: 'Ajouter',
    adm1: 'Province',
    adm2: 'District',
    adm3: 'Commune',
    adm4: 'Village',
    back: 'Retour',
    beneficiaries: 'Bénéficiaires',
    beneficiary: 'Bénéficiaire',
    cancel: 'Annuler',
    close: 'Fermer',
    characters:'Caractères',
    create: 'Créer',
    delete: 'Supprimer',
    details: 'Détails',
    distribution: 'Distribution',
    distributions: 'Distributions',
    done: 'Fin',
    email: 'Email',
    export: 'Export',
    gender: 'Sexe',
    home: 'Accueil',
    households: 'Ménage',
    import: 'Import',
    individual: 'Individual',
    location: 'Lieu',
    new: 'Nouveau',
    next: 'Suivant',
    no_data: 'Pas de données',
    phone: 'Téléphone',
    project: 'Projet',
    projects: 'Projets',
    reports: 'Rapports',
    rights: 'Rôles',
    save: 'Enregistrer',
    settings: 'Paramètres',
    summary:'Sommaire',
    update: 'Modifier',

    // Error
    back_to_homepage: 'Retour à la page d\'accueil',
    error_interceptor_msg: 'Un erreur est survenue, la requête n\'a pas abouti (La réponse de retour est vide).',
    forbidden: 'Page interdite',
    forbidden_message: 'Désolé, vous n\'avez pas l\'autorisation d\'accéder à cette page',
    not_found: 'Page non trouvée',
    not_found_message: 'Désolé, cette page n\'est pas disponible',


    // SPECIFIC VARIABLES


    // Cache
    cache_distribution_added: 'Distribution et bénéficiaires du projet ont été ajoutés dans le cache',
    cache_store_beneficiaries: 'Enregistrer les bénéficiaires',
    cache_no_distribution: 'Cette distribution n\'est pas enregistrée dans le cache, vous ne pouvez pas y accéder hors-ligne',
    

    // Header
    'header_add-beneficiaries': 'Ajouter un ménage',
    'header_add-distribution': 'Ajouter une distribution',
    header_beneficiaries: 'Bénéficiaires',
    'header_data-validation': 'Validation de données',
    header_disconnect: 'déconnexion',
    'header_distributions': 'Distribution',
    header_home: 'Accueil',
    header_import: 'Import de bénéficiaires',
    header_imported: 'Données des bénéficiaires importés',
    header_language: 'langue',
    header_profile: 'Profil',
    header_projects: 'Projets',
    header_reports: 'Rapports',
    header_settings: 'Paramètres',
    'header_update-beneficiary': 'Modifier',


    // Login
    login_bms: 'Beneficiary management system',
    login_forgot_password: 'Mot de passe oublié ?',
    login_password: '*********',
    login_title: 'Connexion',
    login_username: 'identifiant',


    // Model
    model_beneficiaries_dependents: 'Dépendents',
    model_beneficiaries_nationalids: 'Numéro d\'identification',
    model_beneficiaries_phones: 'Téléphones (sans le code pays)',
    model_beneficiaries_status: 'Satut',
    model_commodity: 'Ressource',
    model_commodity_modality: 'Modalité',
    model_commodity_unit: 'Unité',
    model_commodity_value: 'Quantité',
    model_countryIso3: 'Pays',
    model_country_specific: 'Option par pays',
    model_country_specific_field: 'Champ',
    model_criteria: 'Critère',
    model_criteria_operator: 'Condition',
    model_criteria_weight: 'Score du poids',
    model_dateofbirth: 'Date de naissance',
    model_distribution_date: 'Date de la Distribution',
    model_distribution_name: 'Nom',
    model_distribution_type: 'Cible',
    model_donor: 'Donneur',
    model_donor_fullname: 'Nom du donneur',
    model_donor_shortname: 'Surnom',
    model_familyName: 'Nom',
    model_firstName: 'Prénom',
    model_notes: 'Notes',
    model_project_donors_name: 'Donneurs',
    model_project_end_date: 'Date de fin de projet',
    model_project_name: 'Nom  du projet',
    model_project_number_of_households: 'Nombre de ménages',
    model_project_start_date: 'Date de début de projet',
    model_project_value: 'Montant à distribuer',
    model_sector: 'Secteur',
    model_sectors_name: 'Secteurs',
    model_transaction_message: 'Message',
    model_transaction_pickupDate: 'Date de récupération',
    model_transaction_state: 'État',
    model_type: 'Type',
    model_user: 'Utilisateur',
    model_user_password: 'Mot de passe',
    model_value: 'Valeur',
    model_vulnerabilities: 'Vulnérabilités',

    // Profile
    profile_user_change_password: 'Changer de mot de passe',
    profile_user_hint_new_password: 'Nouveau mot de passe',
    profile_user_hint_new_password_again: 'Ré-entrez votre nouveau mot de passe',
    profile_user_hint_old_password: 'Mot de passe actuel',
    profile_user_information: 'Informations utilisateur',

    
    // Settings
    settings_country_specific_options: 'options par pays',
    settings_created: ' créé(e)',
    settings_donors: 'donateurs',
    settings_financial_provider: 'Connexion tiers',
    settings_log_button: 'Recevoir les logs de cet utilisateur par email',
    settings_project_exists: 'Un projet avec le même nom existe déjà',
    settings_users: 'utilisateurs',

    // Snackbar
    snackbar_change_password_done: 'Mot de passe modifié !',
    snackbar_change_password_fail: 'Le mot de passe n\'a pas pu être changé...',
    snackbar_change_password_not_possible: 'Mot de passe pas assez long ou différent de la vérification',


    // Transaction
    transaction_accept_prevention: 'J\'accepte ces conditions.',
    transaction_again: 'Renvoyer',
    transaction_amount_done: 'Quantité envoyée',
    transaction_amount_total: 'Quantité totale',
    transaction_amount_waiting: 'Reste à envoyer',
    transaction_confirm: 'Confirmer la transaction',
    transaction_confirm_button: 'Confirmer',
    transaction_email_code: 'Un email contenant votre code de validation a été envoyé à : ',
    transaction_id_transaction: 'ID Transaction',
    transaction_inProgress: 'Transaction en cours...',
    transaction_paste_code: 'S\'il vous plait, coller le code ici et cliquer sur \'Confirmer\' pour procéder à la transaction',
    transaction_prevention: 'This platform is still under development and the online cash transaction functionality may not be fully stable yet. The development team denies responsibility for any errors that may occur in terms of money loss. By ticking the box below, you agree to use the system knowing fully well its limitations and take responsibility for the results of the transaction.',
    transaction_progress: 'progrès de la distribution des produits:',
    transaction_refresh: 'Vérifier les retraits',
    transaction_transaction: 'Démarrer la transaction',
    transaction_validate_distribution: 'Voulez vous vraiment valider la distribution ? Vous ne serez plus capable de la modifier',
    transaction_validation: 'Confirmer la validation',

    // Tooltip
    tooltip_add_beneficiaries: 'Cette page est la page d\'ajout des bénéficiaires. C\'est un formulaire pour ajouter un nouveau ménage avec des champs obligatoires.',
    tooltip_add_distribution: 'Cette page est la page d\'ajout d\'une distribution. C\'est un formulaire pour ajouter une nouvelle distribution avec des champs obligatoires. Vous allez sélectionner des ménages ou des bénéficiaires en les triant selon un critère de sélection et ajouter un montant spécifique de commodités pour la distribution.',
    tooltip_beneficiaries: 'Cette page est la page des bénéficiaires. Vous pouvez voir tous les ménages du pays. Si vous avez le droit, vous pouvez ajouter de nouveaux ménages avec le bouton "+", gérer des ménages et rechercher dans la liste.',
    tooltip_dashboard: 'Cette page est le tableau de bord. Vous avez une vue générale de chiffres clés à propos du pays et de ses projets. Vous avez accès à une carte avec les distribution du pays ainsi qu\'un résumé des dernières distributions.',
    tooltip_data: 'Cette page est la page d\'après importation des bénéficiaires. C\'est un résumé des ménages que vous avez importé.',
    tooltip_data_validation: 'Cette page est la page d\'import des bénéficiaires en utilisant un fichier. Vous devez vérifier votre fichier en suivant les étapes.',
    tooltip_distributions: 'Cette page est la page de distribution. Vous pouvez voir tous les ménages de la distribution. Si vous avez le droit, vous pouvez ajouter de nouveaux ménages en important un fichier ou en les sélectionnant dans la liste, gérer des ménages et valider la disitrbution pour devenir une transaction.',
    tooltip_import: 'Cette page est la page d\'import des bénéficiaires. Vous pouvez choisir entre importer un nouveau ménage en utilisant un fichier ou l\'API (la source de données externe) pour importer tous les ménages d\'une commune spécifique.',
    tooltip_profile: 'Cette page est la page de profil. Vous pouvez changer votre mot de passe.',
    tooltip_projects: 'Cette page est la page des projets. Vous pouvez voir les projets du pays (seulement ceux dont vous avez le droit de voir). Si vous avez le droit, vous pouvez ajouter une nouvelle distribution avec des ménages qui sont dans le projet, gérer des distributions et des transactions.',
    tooltip_reports: 'Cette page est la page des rapports. Cette page est utilisée pour voir les statistiques du pays, comme la moyenne des transactions d\'un projet, le nombre de distributions d\'un projet...',
    tooltip_settings: 'Cette page est la page des paramètres. Dans cette page, vous pourrez ajouter un nouvel utilisateur, de nouvelle options pour le pays, de nouveaux donneurs, de nouveaux projets et changer les informations de connexion pour les transactions.',
    tooltip_update_beneficiary: 'Cette page est la page de modification des bénéficiaires. C\'est un formulaire pour modifier le ménage selectionné avec des champs obligatoires.',

};
