export const TEXT = {
    // GENERAL VARIABLES

    // Utils
    add: 'Add',
    adm1: 'Province',
    adm2: 'District',
    adm3: 'Commune',
    adm4: 'Village',
    back: 'Back',
    beneficiaries: 'Beneficiaries',
    beneficiary: 'Beneficiary',
    cancel: 'Cancel',
    characters:'Characters',
    close: 'Close',
    create: 'Create',
    delete: 'Delete',
    details: 'Details',
    distribution: 'Distribution',
    distributions: 'Distributions',
    done: 'Done',
    email: 'Email',
    export: 'Export',
    gender: 'Gender',
    home: 'Home',
    households: 'Household',
    import: 'Import',
    individual: 'Individual',
    location: 'Location',
    new: 'New',
    next: 'Next',
    no_data: 'No data',
    phone: 'Phone',
    project: 'Project',
    projects: 'Projects',
    reports: 'Reports',
    rights: 'Rights',
    save: 'Save',
    settings: 'Settings',
    summary:'Summary',
    update: 'Update',

    // Error
    back_to_homepage: 'Go back to homepage',
    error_interceptor_msg: 'An error occured, request has failed (Empty back response).',
    forbidden: 'Forbidden Page',
    forbidden_message: 'Sorry, you don\'t have permission to access this page',
    not_found: 'Page Not Found',
    not_found_message: 'Sorry, this page could not be found',

    // SPECIFIC VARIABLES

    // Cache
    cache_distribution_added: 'Distribution and beneficiaries of the project added in the cache',
    cache_store_beneficiaries: 'Store Beneficiaries',
    cache_no_distribution: 'This distribution isn\'t stored in the cache, you can\'t access it offline',

    // Header
    'header_add-beneficiaries': 'Add Beneficiaries',
    'header_add-distribution': 'Add Distribution',
    header_beneficiaries: 'Beneficiaries',
    header_disconnect: 'log out',
    'header_distributions': 'Distribution',
    'header_data-validation': 'Data Validation',
    header_home: 'Home',
    header_import: 'Import beneficiary data',
    header_imported: 'Imported beneficiaries data',
    header_language: 'language',
    header_profile: 'Profile',
    header_projects: 'Projects',
    header_reports: 'Reports',
    header_settings: 'Settings',
    'header_update-beneficiary': 'Update Beneficiaries',


    // Login
    login_bms: 'Beneficiary management system',
    login_forgot_password: 'Forgot password?',
    login_password: '*********',
    login_title: 'login',
    login_username: 'username',


    // Model
    model_beneficiaries_dependents: 'Dependents',
    model_beneficiaries_nationalids: 'ID Number',
    model_beneficiaries_phones: 'Phones (no country code)',
    model_beneficiaries_status: 'Satus',
    model_commodity: 'Commodity',
    model_commodity_modality: 'Modality',
    model_commodity_unit: 'Unit',
    model_commodity_value: 'Quantity',
    model_countryIso3: 'Country',
    model_country_specific: 'Country specific option',
    model_country_specific_field: 'Field',
    model_criteria: 'Criteria',
    model_criteria_operator: 'Condition',
    model_criteria_weight: 'Score weight',
    model_dateofbirth: 'Date of birth',
    model_distribution_date: 'Date of Distribution',
    model_distribution_name: 'Name',
    model_distribution_type: 'Target',
    model_donor: 'Donor',
    model_donor_fullname: 'Donor\'s name',
    model_donor_shortname: 'Shortname',
    model_familyName: 'Family name',
    model_firstName: 'First name',
    model_notes: 'Notes',
    model_project_donors_name: 'Donors',
    model_project_end_date: 'End Date',
    model_project_name: 'Project\'s name',
    model_project_number_of_households: 'Number of Households',
    model_project_start_date: 'Start Date',
    model_project_value: 'Amount to be distributed',
    model_sector: 'Sector',
    model_sectors_name: 'Sectors',
    model_transaction_message: 'Message',
    model_transaction_pickupDate: 'Pick up date',
    model_transaction_state: 'Status',
    model_type: 'Type',
    model_user: 'User',
    model_user_password: 'Password',
    model_value: 'Value',
    model_vulnerabilities: 'Vulnerabilities',

    // Profile
    profile_user_change_password: 'Change password',
    profile_user_hint_new_password: 'New password',
    profile_user_hint_new_password_again: 'Re-enter new password',
    profile_user_hint_old_password: 'Old password',
    profile_user_information: 'User information',


    // Settings
    settings_country_specific_options: 'country specific options',
    settings_created: ' created',
    settings_donors: 'donors',
    settings_financial_provider: 'Third party connection',
    settings_log_button: 'Get user logs by email',
    settings_project_exists: 'A project with this name already exists',
    settings_users: 'users',

    // Snackbar
    snackbar_change_password_done: 'Password has been changed!',
    snackbar_change_password_fail: 'Could not change password...',
    snackbar_change_password_not_possible: 'Password must be longer than 1 character and match with verification',


    // Transaction
    transaction_accept_prevention: 'I agree to these terms.',
    transaction_again: 'Send again',
    transaction_amount_done: 'Amount sent',
    transaction_amount_total: 'Total amount',
    transaction_amount_waiting: 'Amount picked up',
    transaction_confirm: 'Confirm the transaction',
    transaction_confirm_button: 'Confirm',
    transaction_email_code: 'An email containing your validation code has been sent to:',
    transaction_id_transaction: 'ID Transaction',
    transaction_inProgress: 'Transaction in progress...',
    transaction_paste_code: 'Please paste the code here and click on \'Confirm\' to proceed with the transaction: ',
    transaction_prevention: 'This platform is still under development and the online cash transaction functionality may not be fully stable yet. The development team denies responsibility for any errors that may occur in terms of money loss. By ticking the box below, you agree to use the system knowing fully well its limitations and take responsibility for the results of the transaction.',
    transaction_progress: 'commodity distribution progress:',
    transaction_refresh: 'Check pickup status',
    transaction_transaction: 'Start transaction',
    transaction_validate_distribution: 'Do you really want to validate this distribution ? You won\'t be able to modify it anymore.',
    transaction_validation: 'Confirm the validation',

    // Tooltip
    tooltip_add_beneficiaries: 'This page is the add beneficiaries\' page. This is a form to add a new household with required fields.',
    tooltip_add_distribution: 'This page is the add distribution\'s page. This is a form to add a new distribution with required fields. You will select households or beneficiaries by sorting them by a selection criteria and add a specific amount of commodities to the distribution.',
    tooltip_beneficiaries: 'This page is the beneficiaries\' page. You can see all households of the country. If you have the right, you can add new households with the "+" button, manage households and research in the list.',
    tooltip_dashboard: 'This page is the dashboard. You have a global view on some numbers about the country and its projects. You have access to a map with distributions of the country and summary of last distributions.',
    tooltip_data: 'This page is the post import beneficiaries\' page. This is a summary of households you have imported.',
    tooltip_data_validation: 'This page is the import beneficiaries\' page using a file. You have to verify your file by following the steps.',
    tooltip_distributions: 'This page is the distribution\'s page. You can see all households of the distribution. If you have the right, you can add new households with a file or by selecting in the list, manage households and validate the distribution to a transaction.',
    tooltip_import: 'This page is the import beneficiaries\' page. You can choose to import new households using a file or the API (the external data source) to import all the household of a specific commune.',
    tooltip_profile: 'This page is the profile\'s page. You can change your password.',
    tooltip_projects: 'This page is the projects\' page. You can see all projects of the country (only thoses that you have the right to see). If you have the right, you can add a new distribution with households whose are in the project, manage distributions and transactions.',
    tooltip_reports: 'This page is the reports\' page. This page is used to see statistics of the country, like the average transactions of a projects, number of distributions...',
    tooltip_settings: 'This page is the settings\' page. In this page, you\'ll be able to add a new user, new country specifics, new donors, a new project and change the credential for the transaction.',
    tooltip_update_beneficiary: 'This page is the update beneficiaries\' page. This is a form to update the selected household with required fields.',

};
